language: node_js
node_js:
  - node
  - "8"
  - "6"
  - "4"
git:
  depth: 5
script:
  - ./test/ci
matrix:
  include:
    - node_js: "4"
      install: skip
    - node_js: "0.10"
      install: skip
    - node_js: "0.8"
      install: skip
